# Generated by Django 4.2 on 2023-05-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
