# Generated by Django 4.2 on 2023-05-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_rename_review_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
